# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/cmake-gui

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/frank/Desktop/MyStudies/Lattice_Boltzmann/LB2D_Framework

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/frank/Desktop/MyStudies/Lattice_Boltzmann/LB2D_Framework

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/cmake-gui -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/frank/Desktop/MyStudies/Lattice_Boltzmann/LB2D_Framework/CMakeFiles /home/frank/Desktop/MyStudies/Lattice_Boltzmann/LB2D_Framework/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/frank/Desktop/MyStudies/Lattice_Boltzmann/LB2D_Framework/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named BMP

# Build rule for target.
BMP: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 BMP
.PHONY : BMP

# fast build rule for target.
BMP/fast:
	$(MAKE) -f CMakeFiles/BMP.dir/build.make CMakeFiles/BMP.dir/build
.PHONY : BMP/fast

#=============================================================================
# Target rules for targets named LB2D

# Build rule for target.
LB2D: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 LB2D
.PHONY : LB2D

# fast build rule for target.
LB2D/fast:
	$(MAKE) -f CMakeFiles/LB2D.dir/build.make CMakeFiles/LB2D.dir/build
.PHONY : LB2D/fast

geometry_2D.o: geometry_2D.cpp.o
.PHONY : geometry_2D.o

# target to build an object file
geometry_2D.cpp.o:
	$(MAKE) -f CMakeFiles/LB2D.dir/build.make CMakeFiles/LB2D.dir/geometry_2D.cpp.o
.PHONY : geometry_2D.cpp.o

geometry_2D.i: geometry_2D.cpp.i
.PHONY : geometry_2D.i

# target to preprocess a source file
geometry_2D.cpp.i:
	$(MAKE) -f CMakeFiles/LB2D.dir/build.make CMakeFiles/LB2D.dir/geometry_2D.cpp.i
.PHONY : geometry_2D.cpp.i

geometry_2D.s: geometry_2D.cpp.s
.PHONY : geometry_2D.s

# target to generate assembly for a file
geometry_2D.cpp.s:
	$(MAKE) -f CMakeFiles/LB2D.dir/build.make CMakeFiles/LB2D.dir/geometry_2D.cpp.s
.PHONY : geometry_2D.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/LB2D.dir/build.make CMakeFiles/LB2D.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/LB2D.dir/build.make CMakeFiles/LB2D.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/LB2D.dir/build.make CMakeFiles/LB2D.dir/main.cpp.s
.PHONY : main.cpp.s

third_party/EasyBMP/EasyBMP.o: third_party/EasyBMP/EasyBMP.cpp.o
.PHONY : third_party/EasyBMP/EasyBMP.o

# target to build an object file
third_party/EasyBMP/EasyBMP.cpp.o:
	$(MAKE) -f CMakeFiles/BMP.dir/build.make CMakeFiles/BMP.dir/third_party/EasyBMP/EasyBMP.cpp.o
.PHONY : third_party/EasyBMP/EasyBMP.cpp.o

third_party/EasyBMP/EasyBMP.i: third_party/EasyBMP/EasyBMP.cpp.i
.PHONY : third_party/EasyBMP/EasyBMP.i

# target to preprocess a source file
third_party/EasyBMP/EasyBMP.cpp.i:
	$(MAKE) -f CMakeFiles/BMP.dir/build.make CMakeFiles/BMP.dir/third_party/EasyBMP/EasyBMP.cpp.i
.PHONY : third_party/EasyBMP/EasyBMP.cpp.i

third_party/EasyBMP/EasyBMP.s: third_party/EasyBMP/EasyBMP.cpp.s
.PHONY : third_party/EasyBMP/EasyBMP.s

# target to generate assembly for a file
third_party/EasyBMP/EasyBMP.cpp.s:
	$(MAKE) -f CMakeFiles/BMP.dir/build.make CMakeFiles/BMP.dir/third_party/EasyBMP/EasyBMP.cpp.s
.PHONY : third_party/EasyBMP/EasyBMP.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... BMP"
	@echo "... LB2D"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... geometry_2D.o"
	@echo "... geometry_2D.i"
	@echo "... geometry_2D.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... third_party/EasyBMP/EasyBMP.o"
	@echo "... third_party/EasyBMP/EasyBMP.i"
	@echo "... third_party/EasyBMP/EasyBMP.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

